export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'


export const LOGOUT_USER = 'LOGOUT_USER'

export const UPLOAD_IMAGE="UPLOAD_IMAGE"

export const UPLOAD_IMAGE_REGISTER="UPLOAD_IMAGE_REGISTER"

export const HANDLE_CHANGE="HANDLE_CHANGE"

export const CLEAR_UPLOADS="CLEAR_UPLOADS"


export const CHANGE_PAGE="CHANGE_PAGE"

export const DELETE_IMAGE="DELETE_IMAGE"

export const SUBMIT_BLOG_SUCCESS="SUBMIT_BLOG_SUCCESS"
export const SUBMIT_BLOG_ERROR="SUBMIT_BLOG_ERROR"
export const SUBMIT_BLOG_BEGIN="SUBMIT_BLOG_BEGIN"


export const GET_ALL_BLOGS="GET_ALL_BLOGS"

export const CHANGE_FILTER_CATEGORY="CHANGE_FILTER_CATEGORY"

export const CREATE_COMMENT_BEGIN=" CREATE_COMMENT_BEGIN"
export const CREATE_COMMENT_SUCCESS=" CREATE_COMMENT_SUCCESS"
export const CREATE_COMMENT_ERROR=" CREATE_COMMENT_ERROR"

export const GET_SINGLE_BLOG_COMMENTS="GET_SINGLE_BLOG_COMMENTS"


export const CONVERSATION_ID="CONVERSATION_ID"

export const CREATE_CHAT="CREATE_CHAT"